source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

use_frameworks!

target 'hackameetup' do
    pod 'Alamofire', '~> 4.7'
    pod 'AlamofireImage', '~> 3.3'
    pod 'SwiftyJSON', '~> 4.0'
end

target 'hackameetupTests' do
    pod 'SwiftyJSON', '~> 4.0'
end
